Algoritmo "pol_cm"
// Disciplina   : Lógica de Programação e Algoritimos
// Professor   : Kansehima
// Descrição   : Converte polegadas para centimetros
// Autor(a)    : Maria Fernanda Vaz Romero
// Data atual  : 13/03/2020
Var
// Seção de Declarações das variáveis 
mp , mcm : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe uma medida em polegadas: ")
leia(mp)
mcm <- mp * 2.56
escreva("A medida em cm é: " , mcm)

Fimalgoritmo